// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MessageTest0 struct {
	_tab flatbuffers.Table
}

func GetRootAsMessageTest0(buf []byte, offset flatbuffers.UOffsetT) *MessageTest0 {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MessageTest0{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *MessageTest0) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MessageTest0) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MessageTest0) Data0() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func MessageTest0Start(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func MessageTest0AddData0(builder *flatbuffers.Builder, data0 flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(data0), 0)
}
func MessageTest0End(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
