// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MessageTest2 struct {
	_tab flatbuffers.Table
}

func GetRootAsMessageTest2(buf []byte, offset flatbuffers.UOffsetT) *MessageTest2 {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MessageTest2{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *MessageTest2) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MessageTest2) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MessageTest2) Data0() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MessageTest2) Data1() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MessageTest2) MutateData1(n int32) bool {
	return rcv._tab.MutateInt32Slot(6, n)
}

func (rcv *MessageTest2) Data2() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func MessageTest2Start(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func MessageTest2AddData0(builder *flatbuffers.Builder, data0 flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(data0), 0)
}
func MessageTest2AddData1(builder *flatbuffers.Builder, data1 int32) {
	builder.PrependInt32Slot(1, data1, 0)
}
func MessageTest2AddData2(builder *flatbuffers.Builder, data2 flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(data2), 0)
}
func MessageTest2End(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
