// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package swalprotocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type TopicNetINodePWriteRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsTopicNetINodePWriteRequest(buf []byte, offset flatbuffers.UOffsetT) *TopicNetINodePWriteRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TopicNetINodePWriteRequest{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *TopicNetINodePWriteRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TopicNetINodePWriteRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *TopicNetINodePWriteRequest) TopicID() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *TopicNetINodePWriteRequest) MutateTopicID(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *TopicNetINodePWriteRequest) NetINodeID() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *TopicNetINodePWriteRequest) Offset() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *TopicNetINodePWriteRequest) MutateOffset(n uint64) bool {
	return rcv._tab.MutateUint64Slot(8, n)
}

func (rcv *TopicNetINodePWriteRequest) Length() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *TopicNetINodePWriteRequest) MutateLength(n int32) bool {
	return rcv._tab.MutateInt32Slot(10, n)
}

func (rcv *TopicNetINodePWriteRequest) TransferBackends(j int) []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.ByteVector(a + flatbuffers.UOffsetT(j*4))
	}
	return nil
}

func (rcv *TopicNetINodePWriteRequest) TransferBackendsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func TopicNetINodePWriteRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(5)
}
func TopicNetINodePWriteRequestAddTopicID(builder *flatbuffers.Builder, TopicID uint64) {
	builder.PrependUint64Slot(0, TopicID, 0)
}
func TopicNetINodePWriteRequestAddNetINodeID(builder *flatbuffers.Builder, NetINodeID flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(NetINodeID), 0)
}
func TopicNetINodePWriteRequestAddOffset(builder *flatbuffers.Builder, Offset uint64) {
	builder.PrependUint64Slot(2, Offset, 0)
}
func TopicNetINodePWriteRequestAddLength(builder *flatbuffers.Builder, Length int32) {
	builder.PrependInt32Slot(3, Length, 0)
}
func TopicNetINodePWriteRequestAddTransferBackends(builder *flatbuffers.Builder, TransferBackends flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(TransferBackends), 0)
}
func TopicNetINodePWriteRequestStartTransferBackendsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func TopicNetINodePWriteRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
