// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package solomqprotocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type TopicPrepareRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsTopicPrepareRequest(buf []byte, offset flatbuffers.UOffsetT) *TopicPrepareRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TopicPrepareRequest{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *TopicPrepareRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TopicPrepareRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *TopicPrepareRequest) TopicID() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *TopicPrepareRequest) MutateTopicID(n int64) bool {
	return rcv._tab.MutateInt64Slot(4, n)
}

func (rcv *TopicPrepareRequest) FsINodeID() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *TopicPrepareRequest) MutateFsINodeID(n uint64) bool {
	return rcv._tab.MutateUint64Slot(6, n)
}

func TopicPrepareRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func TopicPrepareRequestAddTopicID(builder *flatbuffers.Builder, TopicID int64) {
	builder.PrependInt64Slot(0, TopicID, 0)
}
func TopicPrepareRequestAddFsINodeID(builder *flatbuffers.Builder, FsINodeID uint64) {
	builder.PrependUint64Slot(1, FsINodeID, 0)
}
func TopicPrepareRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
